# Generated by Django 4.2.7 on 2026-01-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='subdivision',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
